### ISSUE TITLE
Twilio Account Credentials in committed code

### ISSUE THREAD

**Issue by jd4900** [ksmolko/Emergency-Contact#1]
Lines 4 and 5 in `send_sms.py` contain your Twilio account credentials. 

It is best to remove them and replace them with:

```diff
+	account_sid = "ENTER_YOUR_SID_HERE"
+	auth_token = "ENTER_YOUR_TOKEN_HERE"
-	account_sid = "**********************************"
-	auth_token = "**********************************"
```

**Comment by ksmolko** [comment]
Point noted. Created new branch so neither that nor the phone number sits
in the commit history.

**Comment by jd4900** [comment]
Fixes look great. Good call on making a new branch and fixing the numbers exposed in `uart_pi.py`
